NDEV-2267 Restore debug methods
neonlabsorg/tracer-api pull request #67
Opened 2023-10-01 21:54 UTC by stanislav-tkach

Restore and fix the following debug methods that were removed in the https://github.com/neonlabsorg/tracer-api/pull/62 pull request:
- `trace_transaction`
- `debug_traceBlockByNumber`
- `debug_traceBlockByHash methods`

2023-10-02 05:08 UTC, Deniskore requested changes

2023-10-02 05:08 UTC, Deniskore commented on neon-tracer/src/data_source/mod.rs
> +            .await?
I think that requests to proxy should be repeated at least 3 times in general, in case of failure. Under heavy load, the proxy may not return a result, as we have seen earlier.

2023-10-02 12:28 UTC, stanislav-tkach commented on neon-tracer/src/data_source/mod.rs
> +            .await?
It definitely makes sense. I have used the `reqwest_retry` crate to retry the requests.

2023-10-03 06:55 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/mod.rs
> +            .map(serde_json::Value::Array)
Unfortunately, this method does not work correctly, because it executes each transaction on the initial block state.
Instead, it should execute each transaction on the block state left after the previous transaction execution.

The previous implementation did this by sharing the `EmulatorAccountStorage` between transaction executions:
https://github.com/neonlabsorg/neon-evm/blob/develop/evm_loader/lib/src/commands/trace.rs#L81 So I think the trace_block endpoint in neon-api should be restored and used here instead.

The order of transactions in a Solana block is given by the `#` column: https://explorer.solana.com/block/221261763?filter=all

2023-10-03 06:55 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
There is no need for a `ProxyClient`, as the `web3` client does the same thing. It has equivalent methods:
- `self.web3.eth().block_with_txs()` for `eth_getBlockByHash` / `eth_getBlockByNumber`
- `self.web3.eth().transaction()` for `eth_getTransactionByHash`

2023-10-03 07:14 UTC, Deniskore commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
Take into account that web3 does not have a retry and fallback mechanism based on responses from the server, so you'll have to use a third party crate for custom retry policy on futures.

2023-10-03 07:16 UTC, Deniskore commented on neon-tracer/src/data_source/mod.rs
> +            .map(serde_json::Value::Array)
@stanislav-tkach If I remember correctly, @anton-lisanin said he didn't want it in the neon api, correct?

2023-10-03 10:49 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
@stanislav-tkach The Http transport used by `web3` crate has a method `web3::transports::Http::with_client`, where you can provide a custom `reqwest` client configured for retry mechanism.

2023-10-03 14:53 UTC, stanislav-tkach commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
Thanks for the suggestion! Initially I intended to use Neon specific proxy methods, but when I discarded that idea I forgot that I could reuse the web3 client.

2023-10-03 15:23 UTC, stanislav-tkach commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
There is one issue though. The `web3::transports::Http::with_client` constructor accepts the `reqwest::Client` type, but I have `ClientWithMiddleware`.

2023-10-04 09:44 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/mod.rs
> +    pub proxy_client: ProxyClient,
Yes, I saw that too. Then I think we can go with the future retry approach. Implementing a new web3 `Transport` is too complicated and does not justify the effort.

2023-10-11 12:24 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/mod.rs
> +            write_version,
I have a suggestion for how we should compute the Solana transaction index in block. I created a PR on top of this one here: https://github.com/neonlabsorg/tracer-api/pull/72 The details are in the PR description.

2023-10-17 14:03 UTC, andreisilviudragnea reviewed
Please update the pull request description to reflect the latest changes too.

2023-10-17 15:14 UTC, stanislav-tkach commented on neon-tracer/src/data_source/neon_api.rs
> +            .trace(trace_request, id)
Personally I'm a big fan of "field initialization shorthand syntax", so unless you are hardly insisting I prefer to leave this code as it is for now.

2023-10-18 07:38 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/neon_api.rs
> +            .trace(trace_request, id)
I believe the intention of "field initialization shorthand syntax" is to make it more concise to write `new`-style methods:
```rust
struct A {
    f: String,
}

impl A {
    fn new(f: String) -> A {
        A { f }
    }
}

fn init1() {
    let _a = A { f: "".to_string() };
}

fn init2() {
    let f = "".to_string();
    let _a = A { f };
}
```

But this is a case of `init1()` vs `init2()` from this example. The first one is more concise and does the same thing.

Inlining all values results in more indentation, but separate methods can be extracted for different data components. I suggest something along:
```rust
    pub async fn trace_transaction(
        &self,
        transaction: Transaction,
        transaction_index: u64,
        trace_config: Option<TraceConfig>,
        id: u64,
    ) -> Result<Value> {
        self.api_client
            .trace(
                TraceRequestModel {
                    emulate_request: EmulateRequestModel {
                        tx_params: Self::build_tx_params(&transaction),
                        emulation_params: self.build_emulation_params(),
                        slot: transaction.block_number.map(|v| v.as_u64()),
                        tx_index_in_block: if transaction_index == 0 {
                            None
                        } else {
                            Some(transaction_index - 1)
                        },
                    },
                    trace_call_config: Self::build_trace_call_config(trace_config),
                },
                id,
            )
            .await
            .map_err(|e| Error::owned(ErrorCode::InternalError.code(), e.to_string(), None::<()>))
    }

    fn build_tx_params(transaction: &Transaction) -> TxParamsRequestModel {
        TxParamsRequestModel {
            sender: transaction.from.unwrap_or_default().0.into(),
            contract: transaction.to.map(|v| v.0.into()),
            data: Some(transaction.input.0.clone()),
            value: Some(convert_u256(transaction.value)),
            gas_limit: Some(convert_u256(transaction.gas)),
            access_list: None,
        }
    }

    fn build_emulation_params(&self) -> EmulationParamsRequestModel {
        EmulationParamsRequestModel::new(
            Some(self.config.token_mint),
            Some(self.config.chain_id),
            NUM_STEPS_TO_EXECUTE,
            None,
            None,
        )
    }

    fn build_trace_call_config(trace_config: Option<TraceConfig>) -> Option<TraceCallConfig> {
        trace_config.map(|c| TraceCallConfig {
            trace_config: c,
            block_overrides: None,
            state_overrides: None,
        })
    }
```

So I would suggest at least some methods to be extracted from the initial code so it is easier to follow.

2023-10-18 07:40 UTC, andreisilviudragnea commented
@stanislav-tkach The name of the first debug method in the PR description should be `debug_traceTransaction`.

Also, when doing the changes suggested in a code review, please add them in a separate commit so it is easier to check them again, instead of squashing them in the previous commit.

2023-10-18 08:03 UTC, stanislav-tkach commented on neon-tracer/src/data_source/neon_api.rs
> +            .trace(trace_request, id)
Honestly I feel like the new suggestion kind of moves us into the opposite direction from the original one. Sure, it reduces the bloat of the `trace_transaction` function, but at the same time I think that the initialization logic becomes even harder to follow. I believe that the current state is a good middle ground. One again, I will do that if you think it is a crucial change, but personally I prefer the current state.

2023-10-18 09:47 UTC, andreisilviudragnea commented on neon-tracer/src/data_source/neon_api.rs
> +            .trace(trace_request, id)
I am ok with the current state too.

2023-10-18 09:47 UTC, andreisilviudragnea approved these changes

2023-10-18 10:18 UTC, Deniskore approved these changes

2023-10-18 10:18 UTC, merged